### ISSUE TITLE
Please delete after reading

### ISSUE THREAD

**Issue by AJStubbsy** [Dullage/SwitchedSonoffSimple#1]
Hi, I couldn't see an alternative way of contacting you. There's no issue, it's brilliant! I've got this code running on 5 Sonoff, controlling various lights in my house. I'm using the double toggle on one of the downstairs lights to turn off the ones upstairs, which is ace.

Just wanted to say thank you very much for the write up on how to connect the wall switch and for supplying this code.

Top man! Top name!
Cheers
Adam

**Comment by Dullage** [comment]
Hey Adam,

Congrats on the name!

Thanks for taking the time to get in touch here. It’s great to hear my
learnings are helping someone else.

Regards,

Adam
